### GET ALL BOOKS
GET {{BASE_URL}}/books

### GET BOOK BY ID
GET {{BASE_URL}}/books/1

### POST BOOK
POST {{BASE_URL}}/books
Content-Type: application/json

{
  "title": "Harry Potter 1",
  "author": "J.K. Rowling",
  "price": 20,
  "year": 1997
}

### UPDATE BOOK
PUT {{BASE_URL}}/books/1
Content-Type: application/json

{
  "title": "Harry Potter 2",
  "author": "J.K. Rowling",
  "price": 20,
  "year": 1998
}

### DELETE BOOK
DELETE {{BASE_URL}}/books/16

# ----------------- USERS -----------------

### GET ALL USERS
GET {{BASE_URL}}/users

### GET USER BY ID
GET {{BASE_URL}}/users/1

### POST USER
POST {{BASE_URL}}/users
Content-Type: application/json

{
  "username": "user1"
}

### UPDATE USER
PUT {{BASE_URL}}/users/1
Content-Type: application/json

{
  "username": "userA"
}

### DELETE USER
DELETE {{BASE_URL}}/users/16