# ----------------- BOOKS -----------------------------------------------------------------------

### GET ALL BOOKS (LOGIN REQUIRED)
GET {{BASE_URL}}/books
Authorization: Bearer {{JWT_TOKEN}}

### GET BOOK BY ID
GET {{BASE_URL}}/books/3

### POST BOOK
POST {{BASE_URL}}/books
Content-Type: application/json

{
  "title": "Harry Potter 1",
  "author": "J.K. Rowling",
  "price": 30,
  "year": 1998
}

### UPDATE BOOK
PUT {{BASE_URL}}/books/1
Content-Type: application/json

{
  "title": "Harry Potter 2",
  "author": "J.K. Rowling",
  "price": 20,
  "year": 1998
}

### DELETE BOOK
DELETE {{BASE_URL}}/books/16

# ----------------- USERS -----------------------------------------------------------------------

### GET ALL USERS (ADMIN REQUIRED)
GET {{BASE_URL}}/users
Authorization: Bearer {{JWT_TOKEN}}

### GET USER BY ID (ADMIN REQUIRED)
GET {{BASE_URL}}/users/1
Authorization: Bearer {{JWT_TOKEN}}

### POST USER (ADMIN REQUIRED)
POST {{BASE_URL}}/users
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
  "username": "user3",
  "password": "password"
}

### UPDATE USER (ADMIN REQUIRED)
PUT {{BASE_URL}}/users/1
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
  "username": "userA"
}

### DELETE USER (ADMIN REQUIRED)
DELETE {{BASE_URL}}/users/16
Authorization: Bearer {{JWT_TOKEN}}

# ----------------- REVIEWS -----------------------------------------------------------------------

### GET ALL REVIEWS
GET {{BASE_URL}}/reviews

### GET REVIEW BY ID
GET {{BASE_URL}}/reviews/2

### POST REVIEW (JWT-LOGIN REQUIRED)
POST {{BASE_URL}}/reviews
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
  "book_id": 1,
  "rating": 5,
  "comment": "Great book!"
}

### UPDATE REVIEW
PUT {{BASE_URL}}/reviews/1
Content-Type: application/json

{
  "bookId": 3,
  "rating": 4,
  "comment": "Great book!"
}

### DELETE REVIEW
DELETE {{BASE_URL}}/reviews/16


# ----------------- AUTH -----------------------------------------------------------------------

### JWT REGISTER
POST {{BASE_URL}}/auth/register-jwt
Content-Type: application/json

{
  "username": "user1",
  "password": "password"
}

### JWT LOGIN
POST {{BASE_URL}}/auth/login-jwt
Content-Type: application/json

{
  "username": "user1",
  "password": "password"
}

### JWT REFRESH TOKEN
POST {{BASE_URL}}/auth/refresh-jwt
Authorization: Bearer {{JWT_REFRESH_TOKEN}}


# OLD TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNzA5NjU5OTM4LCJqdGkiOiIxYmI3ODdkYS1hMDljLTRmZDUtYTQ1ZC1jZDcwN2Q3MmEzN2YiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjp7ImlkIjoyLCJyb2xlIjoidXNlciJ9LCJuYmYiOjE3MDk2NTk5MzgsImNzcmYiOiI3ZTE3ODkzMS0xNzA5LTQ5MDgtOWVhNy02M2NiMDA2MTZmZGIiLCJleHAiOjE3MDk2NjA4Mzh9.ZjmG7k00QzQGkk8Sb3dbgk3vZoGcTCJIn30ZDLaS-b8