"""add publisher column to book table

Revision ID: 152b69bd5207
Revises: 178f49f844e3
Create Date: 2024-03-05 22:08:28.204745

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '152b69bd5207'
down_revision = '178f49f844e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penerbit', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('penerbit')

    # ### end Alembic commands ###
