"""change column name

Revision ID: c8b921dec68d
Revises: b711d08eb5f5
Create Date: 2024-03-03 18:58:07.426227

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c8b921dec68d'
down_revision = 'b711d08eb5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=500), nullable=True))
        batch_op.drop_column('review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
