"""add year to book table

Revision ID: 2d6ec93e1264
Revises: 0911387f5429
Create Date: 2024-03-03 14:48:41.318119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '2d6ec93e1264'
down_revision = '0911387f5429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # Populate existing rows with dummy email values
    op.execute(text("UPDATE book SET year = 0 WHERE year IS NULL"))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('year', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
