"""delete publisher column

Revision ID: 1f9d317b4a0c
Revises: 1ae0014b536e
Create Date: 2024-03-05 22:35:42.337305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9d317b4a0c'
down_revision = '1ae0014b536e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
